name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: Install Client Dependencies
        run: |
          cd client
          npm install

      - name: Start Server
        run: |
          cd server
          npm start &
      
      - name: Start Client
        run: |
          cd client
          npm start &

      - name: Wait for App to Load
        run: sleep 10

      - name: Install Test Dependencies
        run: |
          cd tests
          npm install

      - name: Run Tests
        run: |
          cd tests
          node runTests.js